name: setup a new page in the sandbox branch
run-name: "sandboxing ${{ vars.LATEST_PAGE_ROUTE }}"
on: [push, workflow_dispatch]

env:
  new_page: ${{ vars.LATEST_PAGE_ROUTE }}

jobs:
  Update-Sandbox-Branch:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hi ${{ env.new_page }}"
      - run: git clone ${{ github.repositoryUrl }}
      - run: cd rep-counter
      - run: ls .
      - run: echo "printing out the root file"
      - run: echo "$(</src/routes/+page.svelte )"
